{{- if and .Values.persistence.createStorageClass -}}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: uid-1000
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Delete
mountOptions: #these options
  - uid=1000
  - gid=1000
volumeBindingMode: Immediate
{{- end }}
